#!/bin/sh
# Turn lib/*.cpy into a C file with the sources as string literals (POSIX sh + sed only).
echo '/* generated by tools/gen_stdlib.sh - do not edit */'
echo 'struct StdlibEntry { const char *name; const char *src; };'
echo 'const struct StdlibEntry g_stdlib[] = {'
for f in "$@"; do
  name=$(basename "$f" .cpy)
  echo "{\"$name\","
  sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/"/' -e 's/$/\\n"/' "$f"
  echo '},'
done
echo '{0, 0}};'
